### ISSUE TITLE
week 5 project assignment - plot formatting and other questions

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#2]
Hi @charliejhadley 
I've pushed my edits with some new plot colors and labels.   Current questions/issues include:
- code chunk 13 facet wrap chart:  the script runs and creates a chart but knitting gets hung up here (line 174)... why?
- how can I label the 'n's next to each bar, add a title and change the fill palette in the facet wrapped chart (code chunk 13, currently commented out to allow knitting)?  The formatting script used for the stacked bar chart version of this chart does not work with facet_wrap applied.... what does work for facet wrap formatting?
- How can I re-order the y-axis labels on my Food and Ethnicity chart (I want 'Yes, a BIG problem' to be at the top of the y-axis)?
- How can I remove the error & script messages that show up in the knitted document?
-   Why does code chunk 14 (currently commented out to allow knitting) not work to create a side by side chart?  The error says %>%<- function isn't found, so I assume I can not create the new object 'facet_plot' from within a tidyverse script - but I'm not able to create facet_plot  after(outside of) the wagap pipe that creates my grouped_ethnicities either because ggplot can't find grouped_ethnicities

There's more, but that's probably enough for one issue!  Thanks so much for helping me sort all this out :)

**Comment by charliejhadley** [comment]
Hey @Jody-O thanks for taking me through the issues - here's my feedback https://share.getcloudapp.com/QwuEEOnD

**Comment by Jody-O** [comment]
Thanks Charlie, that's super helpful.  Can you tell me how can I remove the error & script messages that show up in the knitted document? (you missed that one but I'm guessing you can give me  a quick answer).

Also, when I try knitting the script I pulled with your edits, the side by side chart doesn't show up. 
Thanks again!

**Comment by charliejhadley** [comment]
Ah! Yes, modify the code chunk at the top where the default code chunk options are set to message = FALSE and warnings = FALSE

````
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, 
                      message = FALSE)
```
````
