### ISSUE TITLE
week 6 project assignment questions

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#3]
Hello @charliejhadley, I've pushed my revised code and written 3 questions in code chunk 12 for you to review.
Thank you!

I'll probably add more questions, but thought I would send it now so you don't get all my million questions at once.

**Comment by Jody-O** [comment]
Also... why doesn't my knitted document include the facet plot or the side by side plot?  They seem to work fine when run as script....

**Comment by charliejhadley** [comment]
Hi @Jody-O I've given advice on fixing chunk 12 and explain why the faceted charts don't appear here https://share.getcloudapp.com/llu50rzZ
