### ISSUE TITLE
import-data.R questions

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#4]
Hello @charliejhadley, I've added a script file in the 'data-raw' folder to manipulate my data and saved 2 new .rds files.

Can you tell me why .rds is the preferred file format rather than .csv?

I've also written some questions in the import-data.R script:
line 20
line 60, and 
lines 66-72 (this is the big confusing question about how to re-shape some of the data)  

thanks for your help!

**Comment by charliejhadley** [comment]
Hey @Jody-O! Here's my feedback https://share.getcloudapp.com/YEuR4AW5

It's going to be a bit tricky to split the `reasons_food_is_a_problem` column because some of the responses also include commas, so it's not possible to easily use `separate_rows()`. Do you have a collection of all unique responses that the respondents were able to select? If so then we can use that, otherwise we'll have to think about other solutions.

Feel free to either comment here or to book a chat with me using this link https://savvycal.com/charliejhadley/chat

**Comment by charliejhadley** [comment]
Sorry @Jody-O I forgot to answer your question about .rds vs .csv

The .rds file format has three useful features:
- It keeps R objects exactly the same as they were on export, which has two advantages for tibbles:
    - groups survive the export process
    - list columns survive the export process
- It results in very small data files compared to .csv files
- It is significantly faster to read in an .rds file than it is a .csv file

However, there are important **disadvantage** compared to .csv files.

- .csv files are plain-text files which means that changes are easier to track with git
    - i.e. I can see which lines of a .csv file have changed in a commit, whereas this is not possible with .rds files
- .csv files are ubiquitous and can be read by almost all software and programming languages, whereas .rds files are significantly less common

**Comment by Jody-O** [comment]
Thanks @charliejhadley  I scheduled a chat with you for next Wednesday.  I did a lot of manual data manipulation in Excel to deal with the commas and multiple choice answers for this project originally.  I would set up my surveys differently next time to help avoid the problem with the write-in answers that contain commas.  

I used Google forms to create the survey... do you have a recommendation for a survey tool that spits out data in a more tidy way?

For my existing data, I thought if I could sort to find all the unique responses I could separate (or remove) the write-in responses from the multiple choice responses before combining them all as you did with separate_rows()

BTW I love the separate_rows() command, it's exactly what I was looking for!
