### ISSUE TITLE
project assignment 9 - plot customization questions

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#5]
Hi @charliejhadley 
I re-imported my pre-cleaned data, then had to clean up my .rmd file quite a bit to deal with it.   I think it's working well now, and I like it better without having the long variable names, etc.

I also played around with my food plot - I think it's a bit uglier now actually but I practiced some of the new skills from last week.  I'll try to make it look nicer later.  For now I have some questions.

A simple one first:  how do I get my .rmd plots to show up in the plot window when I run the plot code?  This happens automatically in my course project (WAGAP_poverty_analysis), but not in my Going Deeper with R project (in that project the plot shows up in the .rmd window when code is run, but not in the plot window.

My other 3 questions are commented within my summary_food_plot code (code chunk 10) in my WAGAP-Poverty_and_Food-Report.Rmd

Thanks!

**Comment by charliejhadley** [comment]
Hey @Jody-O thanks for tagging me. I've answered your questions, but I was looking in the wrong place for the first 6 minutes - sorry. https://share.getcloudapp.com/eDujdpd8

Instead of having to pull my code, here's what I wrote

```r
summary_food_plot <- food_challenges_by_ethnicity %>% 
  ggplot(aes(y = is_food_a_challenge,
             x = n,
             fill = race_ethnicity)) +
  geom_col() +
  geom_label(aes(label = scales::percent(pct_of_all_challenge_level_responses, accuracy = 0.1), 
                 x = sum_of_all_challenge_level_responses + 15),
             #  position = position_stack(vjust = .5), THIS LINE NOT NEEDED SINCE LABEL POSITION IS ASSIGNED WITH LABEL ARGUMENT ABOVE
             color = "black", show.legend = FALSE,
             family = "Georgia")  +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Food is a problem for many", 
       x = "number of responses Yes, a BIG problem", 
       y = "Is food a challenge in your community?", fill = "") +
  # theme_ipsum_rc() +
  theme(plot.title = element_text(family = "Georgia"),
        axis.text = element_text(family = "Georgia",
                                 size = 10),
        axis.title = element_text(family = "Georgia"),
        axis.title.y = element_text(hjust = 0),
        legend.text = element_text(family = "Georgia"),
        # QUESTION 2: Why don't the axis titles show up as Georgia font when the axis text and plot title do?  NOTE - To import 'Georgia' I used: library(extrafont)
        #font_import(pattern = "Georgia")
        # windowsFonts(`Georgia` = windowsFont("Georgia"))
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(color = "orange"))
```

**Comment by Jody-O** [comment]
Thanks Charlie, that answered all my questions.... except for the one about why the axis titles will not show up in Georgia font.  I am using Windows so maybe you can't help with this since the problem does not occur on your Mac.  For me axis.title = element_text(family = "Georgia") does not change the axis title font, even though all the other places I change font to Georgia work fine when I use this code:
  theme_ipsum_rc() +
  theme(plot.title = element_text(family = "Georgia"),
        axis.text = element_text(family = "Georgia",
                                  size = 10),
        axis.title = element_text(family = "Georgia"),
        axis.title.y = element_text(hjust = 0),
        legend.text = element_text(family = "Georgia"),

**Comment by Jody-O** [comment]
I figured out a way to change the axis title:

axis.title.y = element_text(family = "Georgia", hjust = 0)
