### ISSUE TITLE
How can I customize a plot after using my custom theme without changing the custom theme?

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#6]
Hi @charliejhadley 
I have a question in code chunk 10 for you about custom themes.
Thanks!

PS - I know my customizations are kinda ugly... but I want code that results in multiple fonts and colors as examples of what is possible in the future...

PSS - I reorganized my files so only the current .Rmd is in the main project folder ( so you should find the right one easily from now on ;)

**Comment by charliejhadley** [comment]
Hi @Jody-O! This issue is because we can't combine element_markdown() and element_text() on the same theme components, which I show here https://share.getcloudapp.com/NQuoqJok
