### ISSUE TITLE
treemap customization questions

### ISSUE THREAD

**Issue by Jody-O** [rin3-spring-2021/WAGAP_poverty_analysis#7]
Hi @charliejhadley!
I've played with the treemap you helped me start and pushed the new .Rmd to github.  I'd like to make it pretty, but it seems like treemapify is somewhat inflexible with color scales and themes... I have 2 questions for you in chunk 14.

Thanks!

**Comment by charliejhadley** [comment]
Hey @Jody-O! Glad to see you building up this treemap. Here's my feedback https://share.getcloudapp.com/wbu6koy8

**Comment by Jody-O** [comment]
Awesome this treemap is getting good now, thanks @charliejhadley!

I have 2 more questions that I can't figure out in  chunk 14 if you have time to look at them.

**Comment by charliejhadley** [comment]
Hey! No worries @Jody-O here's how to customise the continuous colour scale legend https://share.rfor.us/xQu70y6r
